language: python
python:
  - 3.8

services:
  - postgresql

install:
  - pip install -r requirements.txt

script:
  - python manage.py migrate
  - python manage.py test shop/tests/

deploy:
  provider: script
  script: |
    curl -X POST $RENDER_DEPLOY_HOOK_URL  # Вызов хука деплоя Render
    python manage.py loaddata products.yaml  
    python manage.py migrate
  on:
    branch: main
